version: "3"
services:
  servidor:
    container_name: servidor
    restart: always
    build: .
    ports:
      - "5000:3000"
    volumes:
      - .:/app
    environment:
      - BD_HOST=96.43.143.58
      - BD_USER=admin
      - BD_PASSWORD=C0l0mb1@
      - DATABASE=demiles
      - BD_PORT=3306
