version: "3.1"
services:
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: redelite
            MYSQL_PASSWORD: C0l0mb1@
            MYSQL_ROOT_PASSWORD: C0l0mb1@
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - ./db:/var/lib/mysql
        networks:
            - default
        logging:
            driver: none
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mysql
        ports:
            - 8000:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 300M
            MYSQL_USER: root
            MYSQL_PASSWORD: C0l0mb1@
            MYSQL_ROOT_PASSWORD: C0l0mb1@
        logging:
            driver: none
        networks:
            - default
