version: "3.1"
services:
    db:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_PASSWORD: C0l0mb1@
            MYSQL_ROOT_PASSWORD: C0l0mb1@
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./db:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - db:db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: C0l0mb1@
            MYSQL_ROOT_PASSWORD: C0l0mb1@
volumes:
    persistent:
